"""Initial migration

Revision ID: fbad6eba1e93
Revises: 
Create Date: 2025-12-30 21:51:54.167232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbad6eba1e93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('size_sqft', sa.Integer(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=False),
    sa.Column('heating_type', sa.Enum('GAS', 'ELECTRIC', 'OIL', 'HEAT_PUMP', 'SOLAR', name='heatingtype'), nullable=False),
    sa.Column('insulation_level', sa.Enum('MINIMAL', 'MODERATE', 'GOOD', 'EXCELLENT', name='insulationlevel'), nullable=False),
    sa.Column('windows_type', sa.Enum('SINGLE', 'DOUBLE', 'TRIPLE', name='windowstype'), nullable=False),
    sa.Column('roof_type', sa.Enum('FLAT', 'PITCHED', 'METAL', 'TILE', name='rooftype'), nullable=False),
    sa.Column('num_occupants', sa.Integer(), nullable=False),
    sa.Column('monthly_energy_bill', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homes_id'), 'homes', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homes_id'), table_name='homes')
    op.drop_table('homes')
    # ### end Alembic commands ###
